In [2]:
import numpy as np
import time

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [4]:
#execution performance
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x ** 2 for x in py_list]
end = time.time()
print(f'python list time = {end-start} seconds')

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
#vectorization
sq_arr = np_arr ** 2
end = time.time()
print(f'numpy array time = {end-start} seconds')

python list time = 0.11193346977233887 seconds
numpy array time = 0.00471186637878418 seconds


In [7]:
#memory optimisation
import sys

print(f'size of python list = {sys.getsizeof(py_list) * len(py_list)} bytes')
print(f'size of numpy arrays = {np_arr.nbytes} bytes')

size of python list = 8000056000000 bytes
size of numpy arrays = 8000000 bytes


In [13]:
#create numpy arrays
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1,2,3,'suraj'])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

#2-D array
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d, arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' 'suraj'] <class 'numpy.ndarray'> <U21 (4,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [24]:
#create arrays
arr1 = np.zeros((2,3), dtype='int64')
print(arr1, arr1.shape)

arr2 = np.ones((2,3), dtype='int64')
print(arr2, arr2.shape)

arr3 = np.full((2,3), 50)
print(arr3, arr3.shape)

arr4 = np.eye(4) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,11) #range elements
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) # start, end, size but evenly spaced
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[50 50 50]
 [50 50 50]] (2, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[  1.  34.  67. 100.] (4,)


In [29]:
#properties
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr2d.shape)
print(arr2d.size)
print(arr2d.dtype)
print(arr2d.ndim)

float_arr = arr2d.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [31]:
#operations on array
arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D -> 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [36]:
#indexing
arr = np.array([1,2,3,4,5])
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[0], arr[1])
print(arr2d[0][2])

#Fancy indexing
idx = [0,2,3]
print(arr[idx])

#Boolean indexing
print(arr[arr > 3])
print(arr[arr % 2 == 0])

1 2
3
[1 3 4]
[4 5]
[2 4]


In [38]:
#Slicing
arr = np.array([1,2,3,4,5])

print(arr[1:4]) #[start, end, step]
print(arr[1:])
print(arr[:4])
print(arr[:])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]


In [40]:
#copy vs view
nums = [1,2,3,4,5]
sub_list = nums[1:3] #new copy made (separate memory)
print(sub_list)

sub_list[0] = 200
print(sub_list)
print(nums)

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200 #original array changed (view)
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [42]:
#data types
arr = np.array([3 + 5j])
nrr = np.array([2 + 9j])
print(arr, arr.dtype)
print(nrr, nrr.dtype)
print(arr + nrr)

[3.+5.j] complex128
[2.+9.j] complex128
[5.+14.j]


In [47]:
# Multi-demenssional array (2-D)
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2)

print(np.sum(arr2))

sum_of_col = np.sum(arr2, axis = 0)
print(sum_of_col)

sum_of_row = np.sum(arr2, axis = 1)
print(sum_of_row)

print(arr2[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [5]:
#3-D array
arr = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,4], [5,6]]]) #2 x 3 x 2
print(arr)
print(arr.shape)

#indexing
print(arr[0,1,1])

#slicing
print(arr[:, 0, :])
print(arr[:, :, 0])

arr[:, 0, :] = 87
print(arr)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 4]
  [5 6]]]
(2, 3, 2)
4
[[1 2]
 [7 8]]
[[1 3 5]
 [7 9 5]]
[[[87 87]
  [ 3  4]
  [ 5  6]]

 [[87 87]
  [ 9  4]
  [ 5  6]]]


In [9]:
#vectorization
arr = np.array([1,2,3,4,5])
print(arr ** 2) #no use of loop
print(arr + 2)

[ 1  4  9 16 25]
[3 4 5 6 7]


In [11]:
#Broadcasting
arr1 = np.array([1,2,3,4,5]) # 1 X 5
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]]) # 2 X 5
print(arr1 + 5) #broadcasting
print(arr1 + arr2)


[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [15]:
#Normalization
arr = np.array([[1,2], [3,4]])
mean = np.mean(arr)
print(mean) #mean
std_dev = np.std(arr)
print(std_dev) #standard deviation

normalized_arr = (arr - mean) / std_dev
print(normalized_arr) #mean = 0, std approx 1

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [22]:
#mathematical functions
#aggregation
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

45
362880
1
9
0
8
5.0
2.581988897471611
5.0
6.666666666666667


In [25]:
#power functions
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25 36 49 64 81]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[  1   8  27  64 125 216 343 512 729]


In [28]:
#logarithmic functions
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [33]:
#rounding off
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr = np.array([1,2,2,4,4,6,8,8,9])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

3.0
4.0
3.0
3.0
[1 2 4 6 8 9]
[1 2 2 4 4 6 8 8 9]
[1 2 2 4 4 6 8 8 9]
